## Learning pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
## Create Dataframe
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4),
             index=['row1', 'row2', 'row3', 'row4', 'row5'],
             columns=['col1', 'col2', 'col3', 'col4'])

             

In [4]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [5]:
df.tail()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [6]:
df.head(10)

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [39]:
df > 2

col1   col2   col3
row1  False  False  False
row2  False   True   True

In [41]:
df[df['col2']>2]

col1  col2  col3
row2     1   3.0     4

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int64
 1   col2    5 non-null      int64
 2   col3    5 non-null      int64
 3   col4    5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [9]:
df.describe()

col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [11]:
## Indexing
## columnname , rowindex[loc], rowindex column number [.iloc]

df.head()




col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [38]:
df>2

col1   col2   col3
row1  False  False  False
row2  False   True   True

In [15]:
# by using column name

type(df['col1'])

pandas.core.series.Series

In [12]:
df[['col1','col2','col3']]

col1  col2  col3
row1     0     1     2
row2     4     5     6
row3     8     9    10
row4    12    13    14
row5    16    17    18

In [17]:
type(df.loc['row1'])

pandas.core.series.Series

In [19]:
df.loc[['row1','row2']]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7

In [21]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [20]:
df.iloc[2:4, 0:2]

col1  col2
row3     8     9
row4    12    13

In [22]:
df.iloc[2: ,1:]

col2  col3  col4
row3     9    10    11
row4    13    14    15
row5    17    18    19

In [23]:
df.iloc[:,1:] . values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [24]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [25]:
df = pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],
             index=['row1', 'row2'],
             columns=['col1', 'col2', 'col3'])

In [26]:
df

col1  col2  col3
row1     1   NaN     2
row2     1   3.0     4

In [28]:
df.isnull().sum()

col1    0
col2    1
col3    0
dtype: int64

In [32]:
df.isnull() .sum() == 0

col1     True
col2    False
col3     True
dtype: bool

In [ ]:
df['col3'].value_counts()


array([2, 4])

In [37]:
df['col3'].unique()

array([2, 4])