### Numpy Operations

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("Slicing with step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
Slicing with step [2 4 6 8]
Negative indexing 8


In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:", arr[1,2])                 # 0 based indexing  ans :6
print("First Row:", arr[0])                  # ans : [1 2 3]   
print("Second Column:", arr[:,1])          # ans : [2 5 8] 
print("2D Array Slicing:\n", arr[0:2, 1:3])
print("Slicing with step in 2D Array:\n", arr[::2, ::2])    
print("Negative indexing in 2D Array:\n", arr[-1, -2])

2D Array: 6
First Row: [1 2 3]
Second Column: [2 5 8]
2D Array Slicing:
 [[2 3]
 [5 6]]
Slicing with step in 2D Array:
 [[1 3]
 [7 9]]
Negative indexing in 2D Array:
 8


### Sorting

In [7]:
unsorted_arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
print("Unsorted Array:", unsorted_arr) 
sorted_arr = np.sort(unsorted_arr)
print("Sorted Array:", sorted_arr)

Unsorted Array: [3 1 4 1 5 9 2 6 5 3 5]
Sorted Array: [1 1 2 3 3 4 5 5 5 6 9]


## Sorting in 2-D array

In [12]:
arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Unsorted 2D Array:\n", arr_2d_unsorted)
sorted_2d_arr = np.sort(arr_2d_unsorted, axis=0)
print("Sorted 2D Array by columns:\n", sorted_2d_arr)

Unsorted 2D Array:
 [[3 1]
 [1 2]
 [2 3]]
Sorted 2D Array by columns:
 [[1 1]
 [2 2]
 [3 3]]


### Filter with Mask

In [13]:
mask  = arr > 5
print("Numbers greater than 5:", arr[mask])

Numbers greater than 5: [6 7 8 9]


### Fancy indexing vs np.where()

In [16]:
indices = [0,2,4]
print("Fancy Indexing: ", unsorted_arr[indices])  

where_indices = np.where(unsorted_arr > 5)
print("Indices using np.where():", where_indices)

Fancy Indexing:  [3 4 5]
Indices using np.where(): (array([5, 7]),)
