## Numpy array and basics 
learning with chai aur code

In [1]:
import numpy as np

In [10]:
arr_1D = np.array([1,2,3,4,5,6])
print("1D array: ", arr_1D)

arr_2D = np.array([[1,2,3],[4,5,6]])
print("2D array: \n", arr_2D)


1D array:  [1 2 3 4 5 6]
2D array: 
 [[1 2 3]
 [4 5 6]]


In [11]:
py_list = [1,2,3]
print("Python List: ", py_list*2)

np_array = np.array([1,2,3])
print("Python numpy array multiplication: ", np_array * 2)

Python List:  [1, 2, 3, 1, 2, 3]
Python numpy array multiplication:  [2 4 6]


In [13]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print(" List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) *2
print("Numpy operation time: ", time.time() - start)


 List operation time:  0.10035157203674316
Numpy operation time:  0.008689641952514648


In [14]:
zeros = np.zeros((3,4))
print("Array of Zeros: \n", zeros)

Array of Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
ones = np.ones((3,4))
print("Array of Ones: \n", ones)

Array of Ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
full = np.full((3,3), 5)
print("Array of Full: \n", full)

Array of Full: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [22]:
random = np.random.random((3,3))
print("Array of Random: \n", random)

Array of Random: 
 [[7.79980620e-01 1.23770049e-01 8.01599422e-01]
 [7.39068491e-04 6.30812728e-01 8.51227823e-02]
 [3.15987304e-01 1.78890668e-01 7.37810610e-01]]


In [23]:
sequence = np.arange(0,10,2)
print("Array with sequence: \n", sequence)

Array with sequence: 
 [0 2 4 6 8]


### Vector  , Matrix   , Tensor

In [24]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Array of Tensor: \n", tensor)

Array of Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### vector properties

In [26]:
arr = np.array([[1,2,3],[4,5,6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)  
print("Size:", arr.size)
print("Type:", type(arr))   


Shape: (2, 3)
Dimensions: 2
Data Type: int64
Size: 6
Type: <class 'numpy.ndarray'>


### Array reshaping

In [34]:
arr = np.arange(12)
print("Original array: \n", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array (3x3): \n", reshaped)

flattened = reshaped.flatten()
print("Flattened array: \n", flattened)

raveled = reshaped.ravel()
print("Raveled array: \n", raveled)

transposed = reshaped.T
print("Transposed array: \n", transposed)

Original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x3): 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
